blank_issues_enabled: false
contact_links:
  - name: ❓ Usage Question
    url: https://github.com/<your-org>/<your-repo>/discussions
    about: |
      Ask questions and share ideas with other <project-name> community members here.
      If you have a question like "How do I create a new Observational Sampler?" then
      please include a self-contained, reproducible example if possible.